import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/common/header/Header";
import Footer from "./components/common/footer/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  openGraph: {
    title: "Create Nsdfsdfsdext App",
    description: "Generated by create next app",
    url: "https://next-zeni-next.vercel.app/",
    siteName: "Creasdfsdfsfsdfsdte Next App",
    images: [
      {
        url: "/social-preview.png",
        width: 1200,
        height: 630,
        alt: "Create Next App preview image",
      },
    ],
    locale: "en_US",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Create Next App",
    description: "Generated by create next app",
    images: ["/social-preview.png"],
  },
};





export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        <Header />
        <main className="flex-grow bgwh bg-white mx-auto w-full px-4 py-8">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
